version: '3.6'
services:
  influxdb:
    image: influxdb:${latest_influxdb}
    container_name: influxdb
    env_file: 
      - .env
    ports:
      - '8086:8086'
    volumes:
      - ./:/imports 
      - ./influxdb_data:/var/lib/influxdb 
      - ./influxdb/conf/:/etc/influxdb
    environment:
      - INFLUXDB_DB=jmeter
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  grafana:
    image: grafana/grafana:${latest_grafana}
    container_name: grafana
    env_file: 
      - .env    
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
volumes:
  influxdb-storage:
  grafana-storage:
